name: Prod Promote Image
on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  promote:
    name: Prod Promote Container
    uses: mitlibraries/.github/.github/workflows/ecr-multi-arch-promote-prod.yml@main
    secrets: inherit
    with:
      AWS_REGION: "us-east-1"
      GHA_ROLE_STAGE: "quepid-gha-stage"
      GHA_ROLE_PROD: "quepid-gha-prod"
      ECR_STAGE: "quepid-stage"
      ECR_PROD: "quepid-prod"
      DEFAULT_BRANCH: "mit-main"
 